version: 1.0.{build} 
image: Visual Studio 2017

pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script: 
  - cmd: build.bat canary
test: off
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
artifacts:  
- path: .\build\output\_packages\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  server: https://www.myget.org/F/elasticsearch-net-abstractions-temp/api/v2/package
  api_key:
    secure: HBy2VHve+/49OtJlgU1JBDLTkzEnBE0nzeq/F/4crZGY1SAZN6g9r1ofXEduhOS/
  skip_symbols: true
  on:
    branch: master
